### ISSUE TITLE
BrokenPipeError Line 48 in encoder.py

### ISSUE THREAD

**Issue by michaeltoohig** [immstudios/conti#1]
```
INFO        Starting clip <Conti source: wiki>
DEBUG       Executing ffmpeg -hide_banner -i /home/michael/Videos/wiki.mov -filter:a [in]apad[out] -filter:v [in]drawtext=text=wiki:fontsize=48:fontcolor=white:x=(w/2) - (tw/2):y=2*lh:box=1:boxborderw=8:boxcolor=black[out] -s 1920x1080 -pix_fmt yuv420p -r 25 -ar 48000 -t 21.502 -c:v rawvideo -c:a pcm_s16le -max_interleave_delta 400000 -f avi -
DEBUG       Appending <Conti source: wiki> to playlist
Traceback (most recent call last):
  File "conti.py", line 90, in <module>
    conti.start()
  File "/home/michael/Projects/conti/conti/__init__.py", line 64, in start
    self.main_thread()
  File "/home/michael/Projects/conti/conti/__init__.py", line 94, in main_thread
    self.encoder.write(data)
  File "/home/michael/Projects/conti/conti/encoder.py", line 48, in write
    self.proc.stdin.write(data)
BrokenPipeError: [Errno 32] Broken pipe
```

Running the ffmpeg command on its own results with

```
bash: syntax error near unexpected token `('
```

Removing the entire filter section works seems to work. Am I missing something in settings that results in a bad filter? Or something else? 

Thanks

**Comment by michaeltoohig** [comment]
Using your ffmpeg installer script corrected it. I haven't looked further into the reason why your script contains something I didn't have in my earlier ffmpeg installation.

Thanks for providing the scripts.

**Comment by martastain** [comment]
Hello,
our ffmpeg installer provides (among other things) text rendering support using libfontconfig, so the example filter chain probably failed because of this.

I'm glad it works now.
